# This rule is not used by the project liqo-upgrade-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over upgrade.liqo.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: liqo-upgrade-controller
    app.kubernetes.io/managed-by: kustomize
  name: liqoupgrade-admin-role
rules:
- apiGroups:
  - upgrade.liqo.io
  resources:
  - liqoupgrades
  verbs:
  - '*'
- apiGroups:
  - upgrade.liqo.io
  resources:
  - liqoupgrades/status
  verbs:
  - get
