//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoUpgrade) DeepCopyInto(out *LiqoUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoUpgrade.
func (in *LiqoUpgrade) DeepCopy() *LiqoUpgrade {
	if in == nil {
		return nil
	}
	out := new(LiqoUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiqoUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoUpgradeBackup) DeepCopyInto(out *LiqoUpgradeBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoUpgradeBackup.
func (in *LiqoUpgradeBackup) DeepCopy() *LiqoUpgradeBackup {
	if in == nil {
		return nil
	}
	out := new(LiqoUpgradeBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiqoUpgradeBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoUpgradeBackupList) DeepCopyInto(out *LiqoUpgradeBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiqoUpgradeBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoUpgradeBackupList.
func (in *LiqoUpgradeBackupList) DeepCopy() *LiqoUpgradeBackupList {
	if in == nil {
		return nil
	}
	out := new(LiqoUpgradeBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiqoUpgradeBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoUpgradeBackupSpec) DeepCopyInto(out *LiqoUpgradeBackupSpec) {
	*out = *in
	in.BackupTime.DeepCopyInto(&out.BackupTime)
	if in.CRDManifests != nil {
		in, out := &in.CRDManifests, &out.CRDManifests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeploymentManifests != nil {
		in, out := &in.DeploymentManifests, &out.DeploymentManifests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoUpgradeBackupSpec.
func (in *LiqoUpgradeBackupSpec) DeepCopy() *LiqoUpgradeBackupSpec {
	if in == nil {
		return nil
	}
	out := new(LiqoUpgradeBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoUpgradeBackupStatus) DeepCopyInto(out *LiqoUpgradeBackupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoUpgradeBackupStatus.
func (in *LiqoUpgradeBackupStatus) DeepCopy() *LiqoUpgradeBackupStatus {
	if in == nil {
		return nil
	}
	out := new(LiqoUpgradeBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoUpgradeList) DeepCopyInto(out *LiqoUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiqoUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoUpgradeList.
func (in *LiqoUpgradeList) DeepCopy() *LiqoUpgradeList {
	if in == nil {
		return nil
	}
	out := new(LiqoUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiqoUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoUpgradeSpec) DeepCopyInto(out *LiqoUpgradeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoUpgradeSpec.
func (in *LiqoUpgradeSpec) DeepCopy() *LiqoUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(LiqoUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiqoUpgradeStatus) DeepCopyInto(out *LiqoUpgradeStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.PeeringHealthy != nil {
		in, out := &in.PeeringHealthy, &out.PeeringHealthy
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiqoUpgradeStatus.
func (in *LiqoUpgradeStatus) DeepCopy() *LiqoUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(LiqoUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}
